#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server

file_path=$1;
ip_address=$2;
user_name=$3;
path_to_pk=$4;

if [ "$#" -ne 4 ];
then
    echo "Usage: 0-transfer_file file_path ip_address user_name path_to_pk"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$path_to_pk" "$file_path" "$user_name"@"$ip_address":~/
fi
