#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server:

if [ $# -lt 4 ];then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
#Assigning parameters to variables

file_path = $1
ip_address = $2
user_name = $3
path_to_pk = $4

#disabbleing strict host key checking

scp -o "StrictHostKeyChecking = no" -i "$path_to_pk" "$file_path" "$user_name@52.91.147.146:~/"

#checking if the file transfer was successfull

if [$? -eq 0]; then
	echo "file transferred successfully"
else
	echo "file transfer failed try again"
fi
