#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server:

if [ $# -lt 4 ];then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
#Assigning parameters to variables

file_path = $1
ip_address = $2
user_name = $3
path_to_pk = $4

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -gt 3 ]; then
	scp -o StrictHostKeyChecking=no -i "$path_to_pk" "$file_path" "$username@$ip_address:~/"
else
	scp -o StrictHostKeyChecking=no "$file_path" "$user_name@ip_address:~/"
fi
