#!/usr/bin/env bash
# a script showing commands used to Install nginx on your web

sudo apt-get -y update
sudo apt-get install -y nginx

# Ensure nginx is listening to port 80
ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
