#!/usr/bin/env bash
# configuration of web server 1 and 2 to have HTTP Response header 

#update packages first
sudo apt-get update
sudo apt-get install -y nginx

#creating index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#carry out redirection  (301)
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#performing 404 default page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Insert custom Header
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for syntax error
sudo nginx -t

#retsrat the config file
sudo service nginx restart
