#!/usr/bin/env bash

# the task carried out is a s follows:
# Create a script to install and configure HAProxy on lb-01 server (the load balancer)
# Configure HAProxy to send traffic to web-01 and web-02 servers ( (two main web servers)
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 serva
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
my_server_config=\
"
frontend  my_frontend
        bind *:80
        mode http
        default_backend my_backend
backend my_backend
        balance roundrobin
        server 417500-web-01 52.91.147.146:80 check
        server 417500-web-02 3.85.16.39:80 check
"
echo "$my_server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
