#!/usr/bin/env bash
# a bash script that pings an ip address passed to it as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
else
    ip_address=$1
    ping -c 5 "$ip_address"
fi
