#!/usr/bin/env bash
# a bash script that pings an ip address passed to it as an argument
if [ "$1" ]; then
    ip_address=$1
    ping -c 5 "$ip_address"
else
    script_name=$(basename "$0")
    echo "Usage: $script_name {IP_ADDRESS}"
    exit 1
fi
